const PRODUCTS = [
    {
        id: 1,
        brand: 'Toyota',
        name: 'Camry 2024',
        type: 'sedan',
        year: 2024,
        price: 28500,
        image: '🚗',
        specs: ['2.5L Engine', '8-Speed Auto', '32 MPG'],
        rating: 4.8,
        reviews: 247,
        condition: 'New',
        mileage: '5 miles',
        color: 'Pearl White',
        features: ['Bluetooth', 'Backup Camera', 'Lane Assist']
    },
    {
        id: 2,
        brand: 'Honda',
        name: 'Accord Sedan',
        type: 'sedan',
        year: 2023,
        price: 26900,
        image: '🚗',
        specs: ['2.0L Turbo', '10-Speed Auto', '38 MPG'],
        rating: 4.7,
        reviews: 189,
        condition: 'Like New',
        mileage: '12,500 miles',
        color: 'Midnight Blue',
        features: ['Adaptive Cruise', 'Sunroof', 'Premium Audio']
    },
    {
        id: 3,
        brand: 'BMW',
        name: '330i M Sport',
        type: 'luxury',
        year: 2024,
        price: 52400,
        image: '🏎️',
        specs: ['3.0L Twin-Turbo', 'Sport Auto', '35 MPG'],
        rating: 4.9,
        reviews: 156,
        condition: 'New',
        mileage: '8 miles',
        color: 'Alpine White',
        features: ['M Sport Package', 'Premium Leather', 'Panoramic Roof']
    },
    {
        id: 4,
        brand: 'Ford',
        name: 'F-150 SuperCrew',
        type: 'truck',
        year: 2024,
        price: 38900,
        image: '🚙',
        specs: ['3.5L EcoBoost', '10-Speed Auto', '24 MPG'],
        rating: 4.6,
        reviews: 412,
        condition: 'New',
        mileage: '2 miles',
        color: 'Ingot Silver',
        features: ['Towing Package', 'Sync 4', 'Power Steps']
    },
    {
        id: 5,
        brand: 'Tesla',
        name: 'Model 3 Long Range',
        type: 'sedan',
        year: 2024,
        price: 48200,
        image: '⚡',
        specs: ['Dual Motor', 'AWD', '330 mi Range'],
        rating: 4.9,
        reviews: 523,
        condition: 'New',
        mileage: '3 miles',
        color: 'Solid Black',
        features: ['Autopilot', 'Supercharging', '15-inch Display']
    },
    {
        id: 6,
        brand: 'Hyundai',
        name: 'Tucson GLS',
        type: 'suv',
        year: 2024,
        price: 31200,
        image: '🚙',
        specs: ['2.5L Engine', '8-Speed Auto', '31 MPG'],
        rating: 4.5,
        reviews: 287,
        condition: 'New',
        mileage: '6 miles',
        color: 'Calypso Red',
        features: ['All-Wheel Drive', 'Touchscreen', 'Wireless Charger']
    },
    {
        id: 7,
        brand: 'Chevrolet',
        name: 'Corvette Stingray',
        type: 'sports',
        year: 2024,
        price: 65400,
        image: '🏁',
        specs: ['6.2L V8', '8-Speed Automatic', '24 MPG'],
        rating: 4.8,
        reviews: 124,
        condition: 'New',
        mileage: '4 miles',
        color: 'Torch Red',
        features: ['Mid-Engine', 'Performance Seats', 'Ceramic Brakes']
    },
    {
        id: 8,
        brand: 'Mercedes',
        name: 'C-Class Sedan',
        type: 'luxury',
        year: 2023,
        price: 42800,
        image: '👑',
        specs: ['2.0L Turbo', '9-Speed Auto', '33 MPG'],
        rating: 4.7,
        reviews: 198,
        condition: 'Like New',
        mileage: '15,600 miles',
        color: 'Diamond White',
        features: ['Touchscreen', 'Premium Leather', '4MATIC AWD']
    },
    {
        id: 9,
        brand: 'Mazda',
        name: 'CX-5 Preferred',
        type: 'suv',
        year: 2023,
        price: 29400,
        image: '🚙',
        specs: ['2.5L Skyactiv', '6-Speed Auto', '28 MPG'],
        rating: 4.6,
        reviews: 356,
        condition: 'Like New',
        mileage: '18,200 miles',
        color: 'Polymetal Gray',
        features: ['i-Activsense', 'Apple CarPlay', 'AWD']
    },
    {
        id: 10,
        brand: 'Volkswagen',
        name: 'Jetta GLI',
        type: 'sedan',
        year: 2024,
        price: 27500,
        image: '🚗',
        specs: ['2.0L Turbo', '7-Speed DSG', '34 MPG'],
        rating: 4.5,
        reviews: 142,
        condition: 'New',
        mileage: '7 miles',
        color: 'Deep Pearl Black',
        features: ['6-Speed Manual', 'Performance Tuning', 'Touchscreen']
    },
    {
        id: 11,
        brand: 'Audi',
        name: 'A4 Premium Plus',
        type: 'luxury',
        year: 2024,
        price: 50900,
        image: '👑',
        specs: ['2.0L TFSI', '8-Speed Auto', '33 MPG'],
        rating: 4.8,
        reviews: 276,
        condition: 'New',
        mileage: '9 miles',
        color: 'Moonlight Blue',
        features: ['Quattro AWD', 'Virtual Cockpit', 'Premium Plus Package']
    },
    {
        id: 12,
        brand: 'Subaru',
        name: 'Outback Premium',
        type: 'suv',
        year: 2023,
        price: 32100,
        image: '🚙',
        specs: ['2.5L Boxer', 'CVT Auto', '29 MPG'],
        rating: 4.7,
        reviews: 234,
        condition: 'Like New',
        mileage: '16,800 miles',
        color: 'Autumn Green',
        features: ['Standard AWD', 'EyeSight Driver', 'Roof Rails']
    },
    {
        id: 13,
        brand: 'Jeep',
        name: 'Wrangler 4-Door',
        type: 'suv',
        year: 2024,
        price: 42600,
        image: '🚙',
        specs: ['3.6L V6', '8-Speed Auto', '23 MPG'],
        rating: 4.6,
        reviews: 389,
        condition: 'New',
        mileage: '11 miles',
        color: 'Granite Crystal',
        features: ['4WD', 'Removable Top', 'Trail-Rated']
    },
    {
        id: 14,
        brand: 'Nissan',
        name: 'Altima SL',
        type: 'sedan',
        year: 2023,
        price: 26700,
        image: '🚗',
        specs: ['2.5L Engine', 'CVT Transmission', '32 MPG'],
        rating: 4.4,
        reviews: 167,
        condition: 'Like New',
        mileage: '21,500 miles',
        color: 'Super Black',
        features: ['Bluetooth', 'Backup Camera', 'Satellite Radio']
    },
    {
        id: 15,
        brand: 'Lexus',
        name: 'RX 350',
        type: 'luxury',
        year: 2024,
        price: 58900,
        image: '👑',
        specs: ['3.5L V6', '8-Speed Auto', '26 MPG'],
        rating: 4.8,
        reviews: 445,
        condition: 'New',
        mileage: '4 miles',
        color: 'Pearl White',
        features: ['Luxury Package', 'Mark Levinson Audio', 'All-Wheel Drive']
    },
    {
        id: 16,
        brand: 'Dodge',
        name: 'Charger R/T',
        type: 'sports',
        year: 2024,
        price: 47800,
        image: '🏎️',
        specs: ['5.7L V8', '8-Speed Auto', '21 MPG'],
        rating: 4.7,
        reviews: 203,
        condition: 'New',
        mileage: '6 miles',
        color: 'Sting Gray',
        features: ['Muscle Car Performance', 'Super Track Pak', 'Launch Control']
    },
    {
        id: 17,
        brand: 'Porsche',
        name: '911 Carrera',
        type: 'sports',
        year: 2024,
        price: 125400,
        image: '🏁',
        specs: ['3.0L Twin-Turbo', '8-Speed PDK', '28 MPG'],
        rating: 4.9,
        reviews: 87,
        condition: 'New',
        mileage: '2 miles',
        color: 'Racing Yellow',
        features: ['Sport Chrono', 'Premium Interior', 'Air Suspension']
    },
    {
        id: 18,
        brand: 'Kia',
        name: 'Sportage SX',
        type: 'suv',
        year: 2023,
        price: 30200,
        image: '🚙',
        specs: ['2.0L Turbo', '8-Speed Auto', '31 MPG'],
        rating: 4.5,
        reviews: 298,
        condition: 'Like New',
        mileage: '19,400 miles',
        color: 'Snow White Pearl',
        features: ['AWD', 'Touchscreen', 'Panoramic Sunroof']
    },
    {
        id: 19,
        brand: 'GMC',
        name: 'Sierra Denali',
        type: 'truck',
        year: 2024,
        price: 56200,
        image: '🚙',
        specs: ['6.2L V8', '10-Speed Auto', '22 MPG'],
        rating: 4.7,
        reviews: 312,
        condition: 'New',
        mileage: '3 miles',
        color: 'Onyx Black',
        features: ['Denali Premium', 'Multi-Pro Tailgate', 'Adaptive Suspension']
    },
    {
        id: 20,
        brand: 'Infiniti',
        name: 'Q50 Luxe',
        type: 'luxury',
        year: 2023,
        price: 45600,
        image: '👑',
        specs: ['3.0L Twin-Turbo', '7-Speed Auto', '30 MPG'],
        rating: 4.6,
        reviews: 167,
        condition: 'Like New',
        mileage: '14,200 miles',
        color: 'Liquid Platinum',
        features: ['InfinitTouch', 'Premium Audio', 'All-Wheel Drive']
    },
    {
        id: 21,
        brand: 'Volvo',
        name: 'S60 T5',
        type: 'sedan',
        year: 2024,
        price: 44300,
        image: '🚗',
        specs: ['2.0L Turbo', '8-Speed Auto', '32 MPG'],
        rating: 4.6,
        reviews: 134,
        condition: 'New',
        mileage: '5 miles',
        color: 'Midnight Blue',
        features: ['Scandinavian Design', 'Bowers & Wilkins', 'Radar Cruise']
    },
    {
        id: 22,
        brand: 'Acura',
        name: 'RDX Type S',
        type: 'suv',
        year: 2024,
        price: 51200,
        image: '🚙',
        specs: ['3.0L Turbo', '10-Speed Auto', '27 MPG'],
        rating: 4.7,
        reviews: 245,
        condition: 'New',
        mileage: '7 miles',
        color: 'Apex Blue Pearl',
        features: ['Precision All-Wheel Steer', 'Type-S Exterior', 'Premium Sound']
    },
    {
        id: 23,
        brand: 'Cadillac',
        name: 'CT5 Premium',
        type: 'luxury',
        year: 2023,
        price: 41700,
        image: '👑',
        specs: ['2.0L Turbo', '10-Speed Auto', '33 MPG'],
        rating: 4.5,
        reviews: 178,
        condition: 'Like New',
        mileage: '17,300 miles',
        color: 'Stellar Black',
        features: ['Super Cruise', 'Power Panoramic Roof', 'Luxury Package']
    },
    {
        id: 24,
        brand: 'Lincoln',
        name: 'Aviator Grand Touring',
        type: 'suv',
        year: 2024,
        price: 54100,
        image: '🚙',
        specs: ['3.0L Twin-Turbo', '10-Speed Auto', '26 MPG'],
        rating: 4.6,
        reviews: 201,
        condition: 'New',
        mileage: '4 miles',
        color: 'Ebony',
        features: ['Grand Touring Edition', 'Revel Audio', 'Panoramic Glass Roof']
    }
];

// Helper functions for filtering and sorting
function filterProducts(type, price, year) {
    return PRODUCTS.filter(p => {
        let typeMatch = !type || p.type === type;
        let priceMatch = !price || checkPriceRange(p.price, price);
        let yearMatch = !year || p.year === parseInt(year);
        return typeMatch && priceMatch && yearMatch;
    });
}

function checkPriceRange(price, range) {
    if (range === '0-30000') return price <= 30000;
    if (range === '30000-60000') return price > 30000 && price <= 60000;
    if (range === '60000-100000') return price > 60000 && price <= 100000;
    if (range === '100000+') return price > 100000;
    return true;
}

function sortProducts(products, sortBy) {
    let sorted = [...products];
    if (sortBy === 'price-low') sorted.sort((a, b) => a.price - b.price);
    else if (sortBy === 'price-high') sorted.sort((a, b) => b.price - a.price);
    else if (sortBy === 'year') sorted.sort((a, b) => b.year - a.year);
    else if (sortBy === 'featured') sorted = [...PRODUCTS];
    return sorted;
}
